version: 2.1

commands:
  install_dependencies:
    description: "Install dependencies and save cache"
    parameters:
      key:
        type: integer
    steps:
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-waffle-<< parameters.key >>-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-waffle-<< parameters.key >>-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
  setup_solc:
    steps:
      - run:
          name: Setup native solc
          command: sudo cp ~/project/.circleci/solc /bin


jobs:
  lint:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - install_dependencies:
          key: 11
      - run: yarn lint

  test_node_10:
    docker:
      - image: circleci/node:10.18
    steps:
      - checkout
      - setup_remote_docker
      - install_dependencies:
          key: 10
      - setup_solc
      - run: yarn build
      - run: yarn test:others

  test_node_11:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - setup_remote_docker
      - install_dependencies:
          key: 11
      - setup_solc
      - run: yarn build
      - run: yarn test:others

  test_node_12:
    docker:
      - image: circleci/node:12.18
    steps:
      - checkout
      - setup_remote_docker
      - install_dependencies:
          key: 12
      - setup_solc
      - run: yarn build
      - run: yarn test:others

  test_jest_10:
    docker:
      - image: circleci/node:10.18
    steps:
      - checkout
      - setup_remote_docker
      - install_dependencies:
          key: 10
      - setup_solc
      - run: yarn build
      - run: yarn test:jest

  test_jest_11:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout
      - setup_remote_docker
      - install_dependencies:
          key: 11
      - setup_solc
      - run: yarn build
      - run: yarn test:jest

  test_jest_12:
    docker:
      - image: circleci/node:12.18
    steps:
      - checkout
      - setup_remote_docker
      - install_dependencies:
          key: 12
      - setup_solc
      - run: yarn build
      - run: yarn test:jest

  examples:
    working_directory: ~/project/examples
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: cd mock-contracts && yarn install
      - run: cd mock-contracts && yarn lint
      - run: cd mock-contracts && yarn build
      - run: cd mock-contracts && yarn test
      - run:
          name: Install dependencies
          command: cd change-balance && yarn install
      - run: cd change-balance && yarn lint
      - run: cd change-balance && yarn test
      - run:
          name: Install dependencies
          command: cd basic && yarn install
      - run: cd basic && yarn lint
      - run: cd basic && yarn build
      - run: cd basic && yarn test
      - run:
          name: Install dependencies
          command: cd called-on-contract && yarn install
      - run: cd called-on-contract && yarn lint
      - run: cd called-on-contract && yarn build
      - run: cd called-on-contract && yarn test
      - run:
          name: Install dependencies
          command: cd ens && yarn install
      - run: cd ens && yarn lint
      - run: cd ens && yarn test

  example_mock_contracts:
    working_directory: ~/project/examples/mock-contracts
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test

  example_change_balance:
    working_directory: ~/project/examples/change-balance
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: yarn install
      - run: yarn lint
      - run: yarn test

  example_basic:
    working_directory: ~/project/examples/basic
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test

  example_called_on_contract:
    working_directory: ~/project/examples/called-on-contract
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test

  example_ens:
    working_directory: ~/project/examples/ens
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command: yarn install
      - run: yarn lint
      - run: yarn test

  docs:
    working_directory: ~/project/docs
    docker:
      - image: circleci/python:latest
    steps:
      - checkout:
          path: ~/project
      - run:
          name: Install dependencies
          command:
            pip install -r requirements.txt
      - run:
          name: Make html
          command:
            make html

workflows:
  waffle_all:
    jobs:
      - lint
      - test_node_10
      - test_node_11
      - test_node_12
      - test_jest_10
      - test_jest_11
      - test_jest_12
      - examples
      # - example_mock_contracts
      # - example_change_balance
      # - example_basic
      # - example_called_on_contract
      # - example_ens
      - docs
