version: 2
jobs:
  buildandtest:
    docker:
      - image: circleci/node:10.15
    steps:
      - run: checkout
      - run: sudo add-apt-repository ppa:ethereum/ethereum -y
      - run: sudo apt-get update
      - run: apt-cache showpkg solc
      - run: sudo apt-get install solc
      - run: yarn install
      - run: yarn build
      - run: yarn test
      - run: yarn lint
