name: Main CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test-node:
    strategy:
      matrix:
        node: ["12.17", "14.x", "16.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: npm i -g pnpm@6.32.6
      - name: Cache
        uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-packages-waffle-${{ matrix.node }}-{{ checksum "pnpm-lock.yaml" }}
      - run: pnpm install --frozen-lockfile --strict-peer-dependencies
      - name: setup-solc
        run: sudo cp ./.github/workflows/solc /bin
      - run: pnpm run build
      - run: pnpm run test
  docs-and-linter:
    runs-on: ubuntu-latest
    env:
      working-directory: ./docs
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: dependencies
        run: pip install -r requirements.txt
        working-directory: ${{ env.working-directory }}
      - name: Make html
        run: make html
        working-directory: ${{ env.working-directory }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16.14
      - run: npm i -g pnpm@6.20.3
      - run: pnpm install --frozen-lockfile
      - name: linter
        run: pnpm install && pnpm run lint
