name: Main CI
on:
  pull_request:
  push:
    branches:
      - master
jobs:
  test-node:
    strategy:
      matrix:
        node: ["10.x", "12.x", "14.x"]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Cache
        id: cache-node
        uses: actions/cache@v2
        with:
          path: ./.cache/yarn
          key: yarn-packages-waffle-${{ matrix.node }}-{{ checksum "yarn.lock" }}
      - run: yarn install --frozen-lockfile
        if: steps.cache-node.outputs.cache-hit != 'true'
      - name: setup-solc
        run: sudo cp ./.github/workflows/solc /bin
      - run: yarn build
      - run: yarn test:others
  examples:
    runs-on: ubuntu-latest
    env:
      working-directory: ./examples
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - name: Mock-contracts
        run: yarn install && yarn lint && yarn build && yarn test
        working-directory: ${{ env.working-directory }}/mock-contracts
      - name: Change-balance
        run: yarn install && yarn lint && yarn test
        working-directory: ${{ env.working-directory }}/change-balance
      - name: Basic
        run: yarn install && yarn lint && yarn build && yarn test
        working-directory: ${{ env.working-directory }}/basic
      - name: Called-on-contract
        run: yarn install && yarn lint && yarn build && yarn test
        working-directory: ${{ env.working-directory }}/called-on-contract
      - name: Ens
        run: yarn install && yarn lint && yarn test
        working-directory: ${{ env.working-directory }}/ens
  docs-and-linter:
    runs-on: ubuntu-latest
    env:
      working-directory: ./docs
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: dependencies
        run: pip install -r requirements.txt
        working-directory: ${{ env.working-directory }}
      - name: Make html
        run: make html
        working-directory: ${{ env.working-directory }}
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.8
      - run: yarn install --frozen-lockfile
      - name: linter
        run: yarn install
