name: Release

on:
  push:
    branches:
      - master
      - yivlad/changeset-chores

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.0.0
        with:
          # This makes Actions fetch all Git history so that Changesets can generate changelogs with the correct commits
          fetch-depth: 0
          # This allows the changesets/action step to override the default actions user,
          # and allow CI jobs on commits coming from that step.
          # https://github.com/changesets/action/issues/70
          persist-credentials: false

      - name: Setup Node.js 16.x
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 16.x
      - run: npm i -g pnpm@6.32.6
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Set git user
        run: |
          git config user.name truefi-bot
          git config user.email truefi-bot@trusttoken.com

      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm run release
          version: pnpm run version
          commit: "ðŸŽ‰ Release new version"
          title: "ðŸŽ‰ Release new version"
          setupGitUser: false
        env:
          GITHUB_TOKEN: ${{ secrets.GH_BOT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
